### ISSUE TITLE
getMapObjects is returning empty data

### ISSUE THREAD

**Issue by andnp** [stoffern/pokemongo-api#135] opened 2016-08-03 21:37 UTC
If I go to a location that in the past has had lots of forts and pokemon surrounding, I now get no data back from ```getMapObjects```.

Not sure if perhaps the server-side proto changed, because this broke before and after updating my local version of the API.

**Comment by maxnowack** [comment] 2016-08-03 21:59
Same here ...

**Comment by syrys** [comment] 2016-08-03 22:03
i believe its because of the `s2-geometry` update. the new library is buggy and they still havent ironed out all the bugs. ie, if i use NZ lat/lng, i get nothing, i think the library translate my lat/lng to in the middle of nowhere. I think its under active development, so hopefully that should be fixed soon.

**Comment by maxnowack** [comment] 2016-08-03 22:05
Maybe related: AeonLucid/POGOProtos#131

**Comment by syrys** [comment] 2016-08-03 22:16
Actually i just tested my code and you are correct, this is not the issue that i was reffering to. Must me something new.
Yesterday, i still couldnt find anything in NZ, but if i use a US lat/lng like `santa monica pier`, i got some good hits. Today, using the same lat/lng, results in blanks. Hopefully it gets fixed soon. :D

**Comment by maxnowack** [comment] 2016-08-03 22:18
Here's another link to a reddit discussion about this issue: https://www.reddit.com/r/pokemongodev/comments/4w124h/pokemon_go_antibots_reverse_engineering/

**Comment by stoffern** [comment] 2016-08-04 06:45
They have added a MapObjects checksum encryption (AES)
Just need to find the key and we are good to go..

**Comment by delmotte** [comment] 2016-08-04 16:07
not solved yet ?

**Comment by stoffern** [comment] 2016-08-04 17:06
wip

**Comment by delmotte** [comment] 2016-08-05 17:38
is it now ?

**Comment by glmn** [comment] 2016-08-06 02:29
Can't wait :)

**Comment by stoffern** [comment] 2016-08-06 09:20
There are a team of very skilled people working on this as we speak. They have dedicated alot of time and are working almost 24/7 to figure this out.
The problem is a variable sendt called "unknown6" that they have decoded. There is still some work to do.
You can follow them here: https://github.com/pkmngodev/Unknown6

We will update the api when they have completed theyr awsome job

**Comment by andnp** [comment] 2016-08-07 01:25
Looks like things were solved here: https://github.com/keyphact/pgoapi

**Comment by delmotte** [comment] 2016-08-07 08:53
gogogogogo

**Comment by stoffern** [comment] 2016-08-07 09:15
Sorry guys... 2dad9bd0ece461e30c6a0b96567b847094a51ca8

**Closed by stoffern** 2016-08-07 09:15 UTC

**Comment by delmotte** [comment] 2016-08-07 09:29
so disapointed :(

**Comment by syrys** [comment] 2016-08-07 10:13
is this actually solved? Im still getting blanks, maybe due to a different problem?

**Comment by gallexme** [comment] 2016-08-07 10:22
@syrys  @stoffern  stopped working on the api :/
we probably got to fork it
